Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "bento/ubuntu-22.04"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.network "private_network", ip: "192.168.33.10"
    web.vm.provider "parallels" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

  config.vm.define "db" do |db|
    db.vm.box = "bento/ubuntu-22.04"
    db.vm.network "private_network", ip: "192.168.33.11"
    db.vm.provider "parallels" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
  end
end