Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  
  config.vm.network "private_network", ip: "192.168.56.78"
  config.vm.network "public_network"
  
  config.vm.provision "shell", path: "provision.sh"
end